# GAN Configuration

logging:
  level: "INFO"
  file: "logs/app.log"

data:
  n_samples: 1000
  noise_dim: 8
  data_dim: 2
  random_seed: 42

model:
  hidden_dim: 16

training:
  epochs: 2000
  learning_rate_generator: 0.001
  learning_rate_discriminator: 0.001
  batch_size: 64
  d_steps: 1
  g_steps: 1

